### ISSUE TITLE
Error consuming sqs messages

### ISSUE THREAD

**Issue by debjitk** [georgeyk/loafer#54]
I am getting the following error:

> exception (<class 'ValueError'>, ValueError("<loafer.ext.aws.message_translators.SQSMessageTranslator object at 0x10faf1610> failed to translate message={'MessageId': 'd20819f2-406f-4f96-a618-544b477b1a3d', 'ReceiptHandle': 'AQEBFK5WHeaLkDQ2nOLhsr7BBeyVIAsSGManlBfE8i8g5gI5Rh16QkTONbtE+cMgZSzlTnOlLAgzxab3ZSABycM9lQ2HOQtx/x6fc1c3y7VL9f9jwD0jxtU992sPUxtk2uf8I1wACULQh6TbnnK6hXbCB/4yZnWuP09xVlbQhyZTWOPjB//JKsjx6LXphHohmguw++kgzndVIL8FzW8alQACGxu3kXN5nMgFBLSNZYFXEkOJeS/0QaTS7qgK9uIqmFFSEZRGImrMv7CwhBRgFRhKPmrAQAFt3DJHlhyz27WXEuQZm36Jxfb/MMrFaD3rhjpf4p5ZvcnQ7WTA+0+fZ6fTs5nr7TsFCkZfoJS130OjIqxCUoHmo7npWum2Xyt0k4kZQcrwhKBrwlab72D7nnYrkQ==', 'MD5OfBody': '8ca1da029d8479102410a867ed661515', 'Body': '36|0|123456789'}"), <traceback object at 0x111d87870>) received

**Comment by lamenezes** [comment]
@debjitk can you provide more information? e.g. what was the message? the source code of the handler? etc.

**Comment by debjitk** [comment]
handlers.py

`#!/usr/bin/env python

import asyncio
from loafer.ext.aws.handlers import SQSHandler

"""
MessageHandler class
"""


class MessageHandler(SQSHandler):
    def __init__(self):
        pass

    async def handle(self, message, *metadata):
        print("Message received\n")
        # print('message id is {}\n'.format(message["MessageId"]))
        # print('message body is {}\n'.format(message["Body"]))
        # print('args is {}\n\n'.format(args))

        # mimic IO processing
        await asyncio.sleep(0.1)
        return True


"""
ErrorHandler class
"""


class ErrorHandler:
    def __init__(self):
        pass

    async def handle(self, err, message):
        print('exception {} received\n'.format(err))
        # do not delete the message that originated the error
        return False
`

routes.py

`#!/usr/bin/env python

from loafer.ext.aws.routes import SQSRoute
from handlers import MessageHandler, ErrorHandler

"""
Routes
"""


class Route(SQSRoute):
    def __init__(self):
        super(Route, self).__init__('queue-test', {'options': {'WaitTimeSeconds': 3}},
                                    handler=MessageHandler(),
                                    error_handler=ErrorHandler().handle, )
`

main.py

`#!/usr/bin/env python3

from loafer.managers import LoaferManager
from routes import Route

"""
Main
"""
if __name__ == "__main__":
    manager = LoaferManager(routes=Route())
    manager.run(forever=True)
`

**Comment by georgeyk** [comment]
hey @debjitk,

In your Route definition, add something like:

```
from loafer.message_translators import StringMessageTranslator

[...]
super(Route, self).init('queue-test', {'options': {'WaitTimeSeconds': 3}},
handler=MessageHandler(),
error_handler=ErrorHandler().handle, 
message_translator=StringMessageTranslator(),
)
[...]
```

By default it expects the Body content to be a valid json string.
Also, I would suggest not to inherit fromSQSHandler unless you really needed to.

~ :v:

**Comment by georgeyk** [comment]
I'll close this issue, but feel free to reopen it if the suggestion failed in any way.
