### ISSUE TITLE
The library does not work with aiobotocore v0.12.0

### ISSUE THREAD

**Issue by felipegr** [georgeyk/loafer#58]
There's [a change](https://github.com/aio-libs/aiobotocore/pull/769/files#diff-88b99bb28683bd5b7e3a204826ead112L51) in `aiobotocore`'s version `0.12.0` that removes a `loop` parameter from a `get_session` method and it makes `loafer` stop working.

**Comment by georgeyk** [comment]
Thanks @felipegr, I'll take a look.
Could you please add a traceback?

I guess it's not really because of loop parameter since we don't use it directly as well (https://github.com/georgeyk/loafer/blob/master/loafer/ext/aws/bases.py#L26).

**Comment by hartungstenio** [comment]
Hello @georgeyk.

The latest release (1.3.2) came before #48 got merged.

**Comment by felipegr** [comment]
> Hello @georgeyk.
> 
> The latest release (1.3.2) came before #48 got merged.

Yes, in there the `aiobotocore.get_session` method still uses `loop`: https://github.com/georgeyk/loafer/blob/1.3.2/loafer/ext/aws/bases.py#L28

**Comment by georgeyk** [comment]
See https://github.com/georgeyk/loafer/issues/60
