### ISSUE TITLE
Support sentry_sdk

### ISSUE THREAD

**Issue by hartungstenio** [georgeyk/loafer#59]
The library supports sending errors to Sentry, but only using the deprecated [Raven](https://github.com/getsentry/raven-python), and not the new [sentry_sdk](https://github.com/getsentry/sentry-python).

**Comment by georgeyk** [comment]
Thanks. I'll take a look at it.

**Comment by georgeyk** [comment]
@hartungstenio Do you think this should be enough?
https://github.com/georgeyk/loafer/commit/5415657ec9aaa516fb2aa81935e9279d933df73b

**Comment by hartungstenio** [comment]
@georgeyk It seems right.
Out of curiosity: The plan is to drop support for raven in the next release?

**Comment by georgeyk** [comment]
There's a pre-release available (see https://github.com/georgeyk/loafer/issues/60 if you want to check it out).
It seems ok to drop raven support, it's just a thin-wrapper after all and also deprecated by sentry.
Moving from raven to sentry_sdk also seems really simple, so I'm inclined to do so.
