### ISSUE TITLE
Support for aiobotocore >= 1.0.0

### ISSUE THREAD

**Issue by GuilhermeVBeira** [georgeyk/loafer#60]
The old version of aiobotore returns directly to the client when you call the `create_client`. Now with this last version the client needs to be instantiated with an async context manager, broken some pieces because they receive a context generator, not the botocore client:

old version:
https://github.com/aio-libs/aiobotocore/blob/904332b2ab0a3cf44c49af13ac04173a71f9e647/aiobotocore/session.py#L19

new version:
https://github.com/aio-libs/aiobotocore/blob/b86e8ce76c8282fd71b78770b00b7e23a6cf545a/aiobotocore/session.py#L43

**Comment by georgeyk** [comment]
[reposting here for future ref]
As suggested, the rc is available https://pypi.org/project/loafer/2.0.0rc0/
I'll try to create a more stable release soon and any feedback is appreciated.
